server:
  port: 8080
  servlet:
    contextPath:
spring:
  application:
    name: tms-app
  thymeleaf:
    prefix: classpath:/static/
  profiles:
    active: dev
  datasource:
    primary:
      url: jdbc:mysql://localhost:3306/capstone
      username: root
      password: 12345678
      driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 465
    username: nvthohttt47@gmail.com
    password: xmbnpgpsoefuxbvu
    name: Onelink
    protocol: smtp
    defaultEncoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: false
      id:
        new_generator_mappings: true
      physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      connection:
        handling_mode: DELAYED_ACQUISITION_AND_HOLD

endpoints:
  retry:
    interval: 500
    multiplier: 2
    maxAttemps: 4

scheduler:
  enabled: true
  fixedDelay:
    sms: 6000
    firebase: 6000
    email: 6000
    jobOverdue: 6000

driver:
  defaultPassword: 123456aA
